server:
  port: 8083
  servlet:
    context-path: /tijian

logging:
  level:
    org.springframework: debug
    com.neusoft.tijian.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: tijian
    url: jdbc:mysql://localhost:3306/tijian?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.tijian.po