server:
  port: 8082
  servlet:
    context-path: /tijian

logging:
  level:
    org.springframework: debug
    com.neusoft.tijian.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: tijian
    url: jdbc:mysql://localhost:3306/tijian?characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.tijian.po